<#
.SYNOPSIS
    Finds and terminates idle/orphaned VSCode subprocesses (pwsh/conhost/node, etc.).
.DESCRIPTION
    Looks for children of Code.exe, evaluates CPU/age/memory, and optionally kills zombies.
#>

[CmdletBinding(SupportsShouldProcess = $true)]
param(
    [string[]]$ProcessNames = @('pwsh','conhost'),
    [switch]$ExcludeConhost,
    [switch]$KillAll,
    [switch]$ListOnly,
    [int]$MinIdleMinutes = 5,
    [double]$MaxCpuPercent = 0.1,
    [double]$MinMemoryMB = 0,
    [double]$MaxMemoryMB = 0,
    [int[]]$ExcludePIDs = @(),
    [switch]$ShowDetectionDetails,
    [switch]$GracefulShutdown,
    [switch]$IdentifyOrphansOnly,
    [int]$MaxRecentActivitySeconds = 0,
    [int]$KeepMinPwshInstances = 3
)

#Requires -Version 5.1
$script:ProcessCache = @{}
$script:CurrentPID = $PID
$script:Colors = @{ Red='`e[91m'; Green='`e[92m'; Yellow='`e[93m'; Blue='`e[94m'; Cyan='`e[96m'; Reset='`e[0m' }

function Write-ColorOutput { param($Message,[string]$Color='Reset') Write-Host "$($script:Colors[$Color])$Message$($script:Colors['Reset'])" }

function Get-ProcessTree { [CmdletBinding()] param() Write-Verbose 'Building process tree using WMI...'; try { $all=Get-CimInstance -ClassName Win32_Process -Property ProcessId,ParentProcessId,Name,CreationDate,CommandLine; $pt=@{}; foreach($p in $all){$id=[int]$p.ProcessId; $pt[$id]=@{ProcessId=$id;ParentProcessId=if($p.ParentProcessId){[int]$p.ParentProcessId}else{0};Name=$p.Name;CreationDate=$p.CreationDate;CommandLine=$p.CommandLine;Children=[System.Collections.ArrayList]@()}}; foreach($id in $pt.Keys){$p=$pt[$id]; if($p.ParentProcessId -and $pt.ContainsKey($p.ParentProcessId)){ $null=$pt[$p.ParentProcessId].Children.Add($id)}}; Write-Verbose "Process tree built successfully. Total processes: $($pt.Count)"; return $pt } catch { Write-Error "Failed to build process tree: $_"; return @{} } }

function Get-AllDescendants { [CmdletBinding()] param([int]$ProcessId,[hashtable]$ProcessTree) $d=@(); if($ProcessTree.ContainsKey($ProcessId)){ $p=$ProcessTree[$ProcessId]; foreach($c in $p.Children){ $d+=$c; $d+=Get-AllDescendants -ProcessId $c -ProcessTree $ProcessTree }}; return $d }

function Get-VSCodeProcesses { [CmdletBinding()] param() Write-Verbose 'Searching for VSCode (Code.exe) processes...'; try { $vs=Get-Process -Name 'Code' -ErrorAction SilentlyContinue | Where-Object{ $_.ProcessName -eq 'Code' -and $_.Path -like '*VS Code*' }; if(-not $vs){ Write-Warning 'No VSCode (Code.exe) processes found.'; return @() }; Write-Verbose "Found $($vs.Count) VSCode process(es)"; return $vs } catch { Write-Error "Failed to get VSCode processes: $_"; return @() } }

function Get-ProcessStatistics { [CmdletBinding()] param([System.Diagnostics.Process]$Process) try { $now=Get-Date; $age=($now-$Process.StartTime).TotalMinutes; $cpuSec=$Process.CPU; $lifeSec=($now-$Process.StartTime).TotalSeconds; $cpuPct=if($lifeSec -gt 0){($cpuSec/$lifeSec)*100}else{0}; return @{ ProcessId=$Process.Id; Name=$Process.ProcessName; StartTime=$Process.StartTime; AgeMinutes=[math]::Round($age,2); CPU=[math]::Round($cpuSec,2); CpuPercent=[math]::Round($cpuPct,3); WorkingSetMB=[math]::Round($Process.WorkingSet64/1MB,2); PrivateMemoryMB=[math]::Round($Process.PrivateMemorySize64/1MB,2); Path=$Process.Path; CommandLine=$null } } catch { Write-Verbose "Could not get statistics for process $($Process.Id): $_"; return $null } }

function Get-VSCodeSubprocesses { [CmdletBinding()] param([string[]]$FilterNames=@(),[switch]$IncludeAll) $pt=Get-ProcessTree; if($pt.Count -eq 0){ Write-Error 'Failed to build process tree'; return @() }; $vs=Get-VSCodeProcesses; if($vs.Count -eq 0){ return @() }; $all=@(); foreach($v in $vs){ Write-Verbose "Getting descendants for VSCode process $($v.Id)..."; $all+=Get-AllDescendants -ProcessId $v.Id -ProcessTree $pt }; Write-Verbose "Found $($all.Count) total subprocess(es) under VSCode"; $subs=@(); foreach($id in $all|Select-Object -Unique){ try{ $p=Get-Process -Id $id -ErrorAction SilentlyContinue; if($p -and ($IncludeAll -or $FilterNames.Count -eq 0 -or $FilterNames -contains $p.ProcessName)){ $subs+=$p } } catch { Write-Verbose "Could not get process $id (may have exited)" } }; Write-Verbose "Filtered to $($subs.Count) subprocess(es) matching criteria"; return $subs }

function Show-SubprocessList { [CmdletBinding()] param([array]$Subprocesses) Write-ColorOutput "`n=== VSCode Subprocess Report ===" -Color 'Cyan'; Write-ColorOutput "Total subprocesses found: $($Subprocesses.Count)" -Color 'Yellow'; Write-ColorOutput "Current PowerShell PID: $script:CurrentPID (protected)" -Color 'Green'; Write-Host ""; $grouped=$Subprocesses|Group-Object ProcessName|Sort-Object Count -Descending; foreach($g in $grouped){ Write-ColorOutput "`n[$($g.Name)] - $($g.Count) instance(s)" -Color 'Blue'; foreach($p in $g.Group){ $s=Get-ProcessStatistics -Process $p; if($s){ $cur=if($p.Id -eq $script:CurrentPID){' [CURRENT SESSION]'}else{''}; $c=if($p.Id -eq $script:CurrentPID){'Green'}else{'Reset'}; Write-Host "  PID: $($s.ProcessId)$cur" -ForegroundColor $(if($c -eq 'Green'){ 'Green'}else{'White'}); Write-Host "    Age: $($s.AgeMinutes) minutes | CPU: $($s.CpuPercent)% | RAM: $($s.WorkingSetMB) MB"; Write-Host "    Started: $($s.StartTime)" } } }; Write-Host "" }

function Stop-ProcessGracefully { [CmdletBinding()] param([int]$ProcessId,[string]$ProcessName,[int]$GracePeriodSeconds=3) try { if($ProcessName -in 'pwsh','powershell'){ Write-Verbose "Attempting graceful shutdown for $ProcessName PID $ProcessId..." } $p=Get-Process -Id $ProcessId -ErrorAction SilentlyContinue; if($p -and $p.MainWindowHandle -ne [IntPtr]::Zero){ Write-Verbose "Sending close window message to PID $ProcessId..."; $p.CloseMainWindow()|Out-Null; if($p.WaitForExit($GracePeriodSeconds*1000)){ Write-Verbose "Process $ProcessId exited gracefully"; return $true } }; $p=Get-Process -Id $ProcessId -ErrorAction SilentlyContinue; if($p){ Write-Verbose "Grace period expired, force terminating PID $ProcessId..."; Stop-Process -Id $ProcessId -Force -ErrorAction Stop; return $true }; return $true } catch { Write-Verbose "Failed to terminate PID $ProcessId : $_"; return $false } }

function Test-IsOrphanProcess { [CmdletBinding()] param([int]$ProcessId,[hashtable]$ProcessTree) if($ProcessTree.ContainsKey($ProcessId)){ return $ProcessTree[$ProcessId].Children.Count -eq 0 }; return $true }

function Test-IsZombieProcess { [CmdletBinding()] param([hashtable]$ProcessStats,[int]$MinIdleMinutes,[double]$MaxCpuPercent,[double]$MinMemoryMB=0,[double]$MaxMemoryMB=0,[int[]]$ExcludePIDs=@(),[switch]$ShowDetails,[hashtable]$ProcessTree=@{},[switch]$OrphansOnly) $isOldEnough=$ProcessStats.AgeMinutes -ge $MinIdleMinutes; $isIdle=$ProcessStats.CpuPercent -le $MaxCpuPercent; $isNotCurrent=$ProcessStats.ProcessId -ne $script:CurrentPID; $isNotExcluded=$ExcludePIDs.Count -eq 0 -or $ExcludePIDs -notcontains $ProcessStats.ProcessId; $meetsMinMemory=$MinMemoryMB -eq 0 -or $ProcessStats.WorkingSetMB -ge $MinMemoryMB; $meetsMaxMemory=$MaxMemoryMB -eq 0 -or $ProcessStats.WorkingSetMB -le $MaxMemoryMB; $isOrphan=$true; if($OrphansOnly -and $ProcessTree.Count -gt 0){$isOrphan=Test-IsOrphanProcess -ProcessId $ProcessStats.ProcessId -ProcessTree $ProcessTree}; $isZombie=$isOldEnough -and $isIdle -and $isNotCurrent -and $isNotExcluded -and $meetsMinMemory -and $meetsMaxMemory -and $isOrphan; if($ShowDetails -or $VerbosePreference -eq 'Continue'){ $d=@("Process $($ProcessStats.ProcessId) ($($ProcessStats.Name)):","  Age: $($ProcessStats.AgeMinutes)m (need >= ${MinIdleMinutes}m) = $isOldEnough","  CPU: $($ProcessStats.CpuPercent)% (need <= ${MaxCpuPercent}%) = $isIdle","  NotCurrent: $isNotCurrent","  NotExcluded: $isNotExcluded","  Memory: $($ProcessStats.WorkingSetMB)MB"); if($MinMemoryMB -gt 0){$d += "    MinMem: >= ${MinMemoryMB}MB = $meetsMinMemory"}; if($MaxMemoryMB -gt 0){$d += "    MaxMem: <= ${MaxMemoryMB}MB = $meetsMaxMemory"}; if($OrphansOnly){$d += "    IsOrphan: $isOrphan"}; $d += "  => IsZombie: $isZombie"; Write-Verbose ($d -join "`n") }; return $isZombie }

function Remove-ZombieProcesses { [CmdletBinding(SupportsShouldProcess=$true)] param([array]$Processes,[int]$MinIdleMinutes,[double]$MaxCpuPercent,[double]$MinMemoryMB=0,[double]$MaxMemoryMB=0,[int[]]$ExcludePIDs=@(),[switch]$ShowDetails,[hashtable]$ProcessTree=@{},[switch]$OrphansOnly,[switch]$GracefulMode) $zombieCount=0; $terminatedCount=0; $failedCount=0; Write-ColorOutput "`n=== Zombie Process Detection & Termination ===" -Color 'Cyan'; $criteriaMsg="Criteria: Age >= $MinIdleMinutes min, CPU <= $MaxCpuPercent%"; if($MinMemoryMB -gt 0){$criteriaMsg += ", MinRAM >= ${MinMemoryMB}MB"}; if($MaxMemoryMB -gt 0){$criteriaMsg += ", MaxRAM <= ${MaxMemoryMB}MB"}; if($ExcludePIDs.Count -gt 0){$criteriaMsg += ", Excluding PIDs: $($ExcludePIDs -join ',')"}; if($OrphansOnly){$criteriaMsg += ", Orphans Only"}; if($GracefulMode){$criteriaMsg += ", Graceful Shutdown"}; Write-ColorOutput $criteriaMsg -Color 'Yellow'; Write-Host ""; foreach($p in $Processes){ $s=Get-ProcessStatistics -Process $p; if(-not $s){continue}; $testParams=@{ProcessStats=$s;MinIdleMinutes=$MinIdleMinutes;MaxCpuPercent=$MaxCpuPercent;MinMemoryMB=$MinMemoryMB;MaxMemoryMB=$MaxMemoryMB;ExcludePIDs=$ExcludePIDs;ShowDetails=$ShowDetails;ProcessTree=$ProcessTree;OrphansOnly=$OrphansOnly}; if(Test-IsZombieProcess @testParams){ $zombieCount++; $orphanTag=if($OrphansOnly -and (Test-IsOrphanProcess -ProcessId $s.ProcessId -ProcessTree $ProcessTree)){ ' [ORPHAN]' }else{ '' }; Write-ColorOutput "ZOMBIE DETECTED: PID $($s.ProcessId) ($($s.Name))$orphanTag - Age: $($s.AgeMinutes)m, CPU: $($s.CpuPercent)%, RAM: $($s.WorkingSetMB)MB" -Color 'Red'; if($PSCmdlet.ShouldProcess("Process $($s.ProcessId) ($($s.Name))", "Terminate")){ try { if($GracefulMode){ if(Stop-ProcessGracefully -ProcessId $s.ProcessId -ProcessName $s.Name){ Write-ColorOutput "  ✓ Terminated (graceful attempt)" -Color 'Green'; $terminatedCount++ } else { Write-ColorOutput "  ✗ Failed to terminate" -Color 'Yellow'; $failedCount++ } } else { Stop-Process -Id $s.ProcessId -Force -ErrorAction Stop; Write-ColorOutput "  ✓ Terminated successfully" -Color 'Green'; $terminatedCount++ } } catch { Write-ColorOutput "  ✗ Failed to terminate: $_" -Color 'Yellow'; $failedCount++ } } else { Write-ColorOutput "  [WhatIf] Would terminate this process" -Color 'Yellow' } } }; Write-Host ""; Write-ColorOutput "=== Summary ===" -Color 'Cyan'; Write-ColorOutput "Zombies found: $zombieCount" -Color $(if($zombieCount -gt 0){'Red'}else{'Green'}); if(-not $WhatIfPreference){ Write-ColorOutput "Successfully terminated: $terminatedCount" -Color 'Green'; if($failedCount -gt 0){ Write-ColorOutput "Failed to terminate: $failedCount" -Color 'Yellow' } }; Write-Host "" }

# Main
try { Write-ColorOutput "`n=== VSCode Zombie Process Hunter ===" -Color 'Cyan'; Write-ColorOutput "Started at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -Color 'Yellow'; Write-Host ""; if($ExcludeConhost -and -not $PSBoundParameters.ContainsKey('ProcessNames')){ $ProcessNames=@('pwsh'); Write-Verbose "ExcludeConhost specified: removed 'conhost' from default targets" }; $targetNames=if($KillAll){ Write-ColorOutput "Mode: Kill All (targeting all subprocess types)" -Color 'Yellow'; @() } else { Write-ColorOutput "Target processes: $($ProcessNames -join ', ')" -Color 'Yellow'; $ProcessNames }; $subprocesses=Get-VSCodeSubprocesses -FilterNames $targetNames -IncludeAll:$KillAll; if($subprocesses.Count -eq 0){ Write-ColorOutput "No matching subprocesses found." -Color 'Green'; exit 0 }; if($KeepMinPwshInstances -gt 0){ $pwshInstances=@($subprocesses|Where-Object{$_.ProcessName -eq 'pwsh'}|Sort-Object StartTime -Descending); if($pwshInstances.Count -gt 0){ $protectedPwshPIDs=@($pwshInstances|Select-Object -First $KeepMinPwshInstances|ForEach-Object{$_.Id}); Write-ColorOutput "Copilot safety guard: protecting $($protectedPwshPIDs.Count) most-recent pwsh PID(s): $($protectedPwshPIDs -join ', ')" -Color 'Green'; $ExcludePIDs=($ExcludePIDs+$protectedPwshPIDs)|Sort-Object -Unique } }; $processTree=if($IdentifyOrphansOnly){ Get-ProcessTree } else { @{} }; if($ListOnly){ Show-SubprocessList -Subprocesses $subprocesses; Write-ColorOutput "List-only mode: No processes were terminated." -Color 'Green' } else { if(-not $KillAll -and $ProcessNames.Count -gt 0){ Show-SubprocessList -Subprocesses $subprocesses }; $removeParams=@{ Processes=$subprocesses; MinIdleMinutes=$MinIdleMinutes; MaxCpuPercent=$MaxCpuPercent; MinMemoryMB=$MinMemoryMB; MaxMemoryMB=$MaxMemoryMB; ExcludePIDs=$ExcludePIDs; ShowDetails=$ShowDetectionDetails; ProcessTree=$processTree; OrphansOnly=$IdentifyOrphansOnly; GracefulMode=$GracefulShutdown }; Remove-ZombieProcesses @removeParams }; Write-ColorOutput "Completed at: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')" -Color 'Yellow' } catch { Write-Error "An error occurred: $_"; Write-Error $_.ScriptStackTrace; exit 1 }
